var lesson = [ 
    
        {
          "id": 1,
          "name": "Math Class",
          "location": "Ilford",
          "Price": 30,
          "image": "./Images/math1.jpeg",
          "availableInventory": 5,
          "message": "",
          "rating": 5,
        },
        {
          "id": 2,
          "name": "English Class",
          "location": "Manor Park",
          "Price": 35,
          "image": "./Images/english1.png",
          "availableInventory": 5,
          "message": "",
          "rating": 4,
        },
        {
          "id": 3,
          "name": "Science Class",
          "location": "Romford",
          "Price": 35,
          "image": "./Images/science1.png",
          "availableInventory": 5,
          "message": "",
          "rating": 4,
        },
        {
          "id": 4,
          "name": "Social Science Class",
          "location": "Brentwood",
          "Price": 25,
          "image": "./Images/social1.gif",
          "availableInventory": 5,
          "message": "",
          "rating": 3,
        },
        {
          "id": 5,
          "name": "Dance Class",
          "location": "Liverpool Street",
          "Price": 45,
          "image": "./Images/dance.png",
          "availableInventory": 5,
          "message": "",
          "rating": 4,
        },
        {
          "id": 6,
          "name": "Drawing Class",
          "location": "Seven Kings",
          "Price": 30,
          "image": "./Images/drawing1.jpg",
          "availableInventory": 5,
          "message": "",
          "rating": 5,
        },
        {
          "id": 7,
          "name": "Music Class",
          "location": "Shenfield",
          "Price": 45,
          "image": "./Images/music.jpg",
          "availableInventory": 5,
          "message": "",
          "rating": 4,
        },
        {
          "id": 8,
          "name": "Drama Class",
          "location": "Manchester",
          "Price": 45,
          "image": "./Images/drama1.png",
          "availableInventory": 5,
          "message": "",
          "rating": 3,
        },
        {
          "id": 9,
          "name": "Football Class",
          "location": "Woodford",
          "Price": 50,
          "image": "./Images/football.png",
          "availableInventory": 5,
          "message": "",
          "rating": 5,
        },
        {
          "id": 10,
          "name": "Karate Class",
          "location": "BrentCross",
          "Price": 40,
          "image": "./Images/karate.png",
          "availableInventory": 5,
          "message": "",
          "rating": 4,
        },
        {
          "id": 11,
          "name": "Badminton Class",
          "location": "Moorgate",
          "Price": 35,
          "image": "./Images/badminton.png",
          "availableInventory": 5,
          "message": "",
          "rating": 5,
        },
        {
          "id": 12,
          "name": "Gymnastic Class",
          "location": "Hendon",
          "Price": 35,
          "image": "./Images/gymnastic.png",
          "availableInventory": 5,
          "message": "",
          "rating": 3,
        }
      ]
      

